// Token Types 
const TKN_INT = 'INT';
const TKN_FLOAT = 'FLOAT';
const TKN_PLUS = 'PLUS';
const TKN_MINUS = 'MINUS';
const TKN_MUL = 'MUL';
const TKN_DIV = 'DIV';
const TKN_EXPONENT = 'EXPONENT';
const TKN_LPAREN = 'LPAREN';
const TKN_RPAREN = 'RPAREN';
const DIGITS = '0123456789';
const TKN_EOF = 'EOF';

export { TKN_EOF, TKN_INT, TKN_FLOAT, TKN_PLUS, TKN_MINUS, TKN_MUL, TKN_DIV, TKN_EXPONENT, TKN_LPAREN, TKN_RPAREN, DIGITS}